apiVersion: v1
kind: Service
metadata:
  name: ppegelow
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 9000
  selector:
    app: ppegelow
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ppegelow
spec:
  selector:
    matchLabels:
      app: ppegelow
      tier: backend
  replicas: 1
  template:
    metadata:
      labels:
        app: ppegelow
        tier: backend
    spec:
      containers:
      - name: ppegelow
        imagePullPolicy: Always
        image: pegelow/greeter:latest
        ports:
        - containerPort: 9000
        env:
        - name: MY_SERVICE_NAME
          value: ppegelow


